const root=document.getElementById('root');
const channel=new BroadcastChannel('lacuenta-demo');
const products=[['Hamburguesa vegana',490],['Papas rústicas',260],['Refresco',180],['Agua mineral',140],['Pizza muzzarella',620],['Café',130]];
const fresh=()=>({table:8,waiter:'Martín',status:'open',items:[['Hamburguesa vegana',490,2],['Papas rústicas',260,1],['Refresco',180,2]].map(([name,price,qty])=>({id:crypto.randomUUID(),name,price,qty,paidQty:0})),payments:[]});
let state=JSON.parse(localStorage.getItem('lacuenta-state')||'null')||fresh();
let role=new URLSearchParams(location.search).get('role')==='restaurant'?'restaurant':'customer';
let selected={},tip=10,method='Tarjeta';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(n);
const save=()=>{localStorage.setItem('lacuenta-state',JSON.stringify(state));channel.postMessage(state);render()};
channel.onmessage=e=>{state=e.data;render()};
const icon={phone:'▣',chef:'♨',card:'▤',wallet:'◈',cash:'▥',check:'✓',plus:'＋',users:'●',receipt:'▧',qr:'▦',reset:'↻',split:'⑂'};
function shell(content){return `<div class="app-shell"><header class="topbar"><div class="brand"><span>LaCuenta</span><b>!</b></div><div class="role-switch"><button data-role="customer" class="${role==='customer'?'active':''}">${icon.phone} Cliente</button><button data-role="restaurant" class="${role==='restaurant'?'active':''}">${icon.chef} Restaurante</button></div></header>${content}</div>`}
function customer(){
 const remaining=state.items.reduce((s,i)=>s+(i.qty-i.paidQty)*i.price,0),selectedTotal=state.items.reduce((s,i)=>s+(selected[i.id]||0)*i.price,0),tipAmount=Math.round(selectedTotal*tip/100);
 return shell(`<main class="customer-page"><section class="hero-card"><div><small>LA ESQUINA · COLONIA</small><h1>Mesa ${state.table}</h1><p>Te atiende ${state.waiter}</p></div><div class="live"><span></span> Cuenta en vivo</div></section>
 <section class="card"><div class="section-title"><div><h2>Tu consumo</h2><p>Elegí qué querés pagar</p></div><button class="text-btn" id="select-all">Seleccionar todo</button></div><div class="items">${state.items.map(i=>{const a=i.qty-i.paidQty,c=selected[i.id]||0;return `<div class="item ${a===0?'paid-item':''}"><div class="item-info"><b>${i.name}</b><span>${money(i.price)} c/u</span>${i.paidQty?`<em>${i.paidQty} pagado${i.paidQty>1?'s':''}</em>`:''}</div>${a?`<div class="stepper"><button data-dec="${i.id}">−</button><strong>${c}</strong><button data-inc="${i.id}">+</button></div>`:`<div class="paid-label">${icon.check} Pagado</div>`}</div>`}).join('')}</div></section>
 <section class="card payment-card"><h2>Propina</h2><div class="tip-grid">${[0,5,10,15].map(n=>`<button data-tip="${n}" class="${tip===n?'active':''}">${n===0?'Sin propina':n+'%'}</button>`).join('')}</div><h2>Forma de pago</h2><div class="methods">${[['Tarjeta',icon.card],['Mercado Pago',icon.wallet],['Efectivo',icon.cash]].map(([m,ic])=>`<button data-method="${m}" class="${method===m?'active':''}"><b>${ic}</b><span>${m}</span></button>`).join('')}</div><div class="summary"><div><span>Seleccionado</span><b>${money(selectedTotal)}</b></div><div><span>Propina</span><b>${money(tipAmount)}</b></div><div class="total"><span>Total a pagar</span><b>${money(selectedTotal+tipAmount)}</b></div></div><button class="primary" id="pay" ${selectedTotal?'':'disabled'}>Pagar ahora</button><p class="remaining">Saldo restante de la mesa: <b>${money(remaining)}</b></p></section></main>`)}
function restaurant(){const total=state.items.reduce((s,i)=>s+i.qty*i.price,0),paid=state.payments.reduce((s,p)=>s+p.amount,0),tips=state.payments.reduce((s,p)=>s+p.tip,0);return shell(`<main class="restaurant-page"><aside class="sidebar"><div class="restaurant-name"><b>${icon.chef}</b><div><b>La Esquina</b><span>Panel del restaurante</span></div></div><nav><button class="active">${icon.users} Mesas</button><button>${icon.receipt} Pagos</button><button>${icon.qr} Códigos QR</button></nav><button class="reset" id="reset">${icon.reset} Reiniciar demo</button></aside><section class="dashboard"><div class="dash-header"><div><small>SALÓN PRINCIPAL</small><h1>Mesa ${state.table}</h1><p>Mozo: ${state.waiter}</p></div><div class="status ${state.status}">${state.status==='paid'?'Pagada':'Cuenta abierta'}</div></div><div class="stats"><div><span>Total</span><b>${money(total)}</b></div><div><span>Pagado</span><b>${money(paid)}</b></div><div><span>Pendiente</span><b>${money(total-paid)}</b></div><div><span>Propinas</span><b>${money(tips)}</b></div></div><div class="dashboard-grid"><section class="card order-panel"><div class="section-title"><div><h2>Cuenta actual</h2><p>Los cambios aparecen en la pantalla del cliente</p></div><div class="live"><span></span> Sincronizado</div></div><div class="restaurant-items">${state.items.map(i=>`<div><div><b>${i.qty}× ${i.name}</b><span>${i.paidQty}/${i.qty} pagados</span></div><strong>${money(i.qty*i.price)}</strong></div>`).join('')}</div></section><section class="card add-panel"><h2>Agregar producto</h2><p>Simula la carga desde un POS gastronómico.</p><div class="product-grid">${products.map(([n,p])=>`<button data-product="${n}"><b>${icon.plus}</b><span>${n}</span><strong>${money(p)}</strong></button>`).join('')}</div></section></div><section class="card payments-panel"><h2>Pagos recibidos</h2>${state.payments.length?`<div class="payment-list">${[...state.payments].reverse().map(p=>`<div><div><b>${p.method}</b><span>${new Date(p.at).toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'})} · Propina ${money(p.tip)}</span></div><strong>${money(p.amount)}</strong></div>`).join('')}</div>`:`<div class="empty"><b>${icon.split}</b><p>Todavía no se registraron pagos.</p></div>`}</section></section></main>`)}
function render(){root.innerHTML=role==='customer'?customer():restaurant();bind()}
function bind(){document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;render()});if(role==='customer'){
 document.getElementById('select-all').onclick=()=>{selected=Object.fromEntries(state.items.map(i=>[i.id,i.qty-i.paidQty]));render()};
 document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{const i=state.items.find(x=>x.id===b.dataset.inc),a=i.qty-i.paidQty;selected[i.id]=Math.min((selected[i.id]||0)+1,a);render()});
 document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{selected[b.dataset.dec]=Math.max((selected[b.dataset.dec]||0)-1,0);render()});
 document.querySelectorAll('[data-tip]').forEach(b=>b.onclick=()=>{tip=+b.dataset.tip;render()});document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{method=b.dataset.method;render()});
 const pay=document.getElementById('pay');pay.onclick=()=>{const amount=state.items.reduce((s,i)=>s+(selected[i.id]||0)*i.price,0);if(!amount)return;const tipValue=Math.round(amount*tip/100);state.items=state.items.map(i=>({...i,paidQty:i.paidQty+(selected[i.id]||0)}));state.status=state.items.some(i=>i.paidQty<i.qty)?'open':'paid';state.payments.push({id:crypto.randomUUID(),amount,tip:tipValue,method,at:new Date().toISOString()});selected={};save();alert('Pago registrado correctamente');};
 }else{document.getElementById('reset').onclick=()=>{state=fresh();save()};document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{const [name,price]=products.find(p=>p[0]===b.dataset.product),found=state.items.find(i=>i.name===name&&i.paidQty===0);if(found)found.qty++;else state.items.push({id:crypto.randomUUID(),name,price,qty:1,paidQty:0});state.status='open';save()})}}
render();
